# Author: Chris Ward <chris@calmrat.com.>
services:
  web:
    build: .
    container_name: qrypto-web
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    #environment:
    # see DOTenv -> .env file in project root
    # see README.md for more details.

    command: ["./start.sh"]

  db:
    image: postgres:15
    container_name: qrypto-db
    restart: always
    environment:
      POSTGRES_DB: qrypto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: qrypto-redis
    ports:
      - "6379:6379"

  test:
    build: .
    container_name: qrypto-test
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: