# Author: Chris Ward <chris@calmrat.com.>
# Description: Docker Compose file for Qrypto
# License: MIT

version: "3.13"

services:
  qrypto:
    build: .
    container_name: qrypto
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./qrypto/data/cache:/app/qrypto/data/cache
      - ./logs:/app/logs
    restart: always
